electricity <- read.table ("household_power_consumption.txt", sep = ";", header = TRUE,colClasses = "character")
head (electricity)
data <- subset (electricity, Date == "1/2/2007" | Date == "2/2/2007")
data$Date <- as.Date (data$Date, format = "%d/%m/%Y")
data$newdate <- strptime (paste(data$Date, data$Time), format = "%Y-%m-%d %H:%M:%S")
data$days <- weekdays (data[,"newdate"], abbreviate = TRUE)
png(file = "Plot1.png")
data[,3] <- as.numeric(data[,3])
hist (data$Global_active_power, col= "red", main = "Global Active Power",xlab = "Global Active Power(kilo watts)")
dev.off()